#####################################################
# Install packages if you didn't install them yet
# (note: if you’re not sure whether a package is already installed, try to load is first using the library() function. 
# R will throw an error if not installed
install.packages("ggplot2", dependencies=TRUE)
install.packages("car", dependencies=TRUE)
install.packages("pastecs", dependencies=TRUE)
install.packages("psych", dependencies=TRUE)
install.packages("grid", dependencies=TRUE)
install.packages("gridExtra", dependencies=TRUE)
install.packages("DescTools", dependencies=TRUE)
install.packages("Hmisc", dependencies=TRUE)
install.packages("reshape2", dependecies=TRUE)
install.packages("ez",dependencies = TRUE)
install.packages("multcomp",dependencies = TRUE)
install.packages("nlme",dependencies = TRUE)
install.packages("ez",dependencies = TRUE)
install.packages("MASS",dependencies = TRUE)
install.packages("lme4",dependencies = TRUE)
install.packages("emmeans",dependencies = TRUE)
install.packages("afex",dependencies = TRUE)
install.packages("ggbeeswarm",dependencies = TRUE)
install.packages("gmodels",dependencies = TRUE)
install.packages("dplyr",dependencies = TRUE)
install.packages("ggpubr",dependencies = TRUE)
install.packages("readxl",dependencies = TRUE)
install.packages("tidyverse",dependencies = TRUE)
install.packages("stringr",dependencies = TRUE)
install.packages("scatterplot3d") # Install

# Load packages
library(nlme)
library(multcomp)
library(Hmisc)
library(DescTools)
library(ggplot2)
library(car)
library(pastecs)
library(psych)
library(grid)
library(gridExtra)
library(reshape2)
library(lme4)
library(MASS)
library(emmeans)
library(ez)
library(afex)
library(ggbeeswarm)
library(gmodels)
library(dplyr)
library(ggpubr)
library(readxl)
library(tidyverse)
library(stringr)
library(scatterplot3d) # load